---
 apiVersion: extensions/v1beta1
 kind: Deployment
 metadata:
   name: crudapp
 spec:
   replicas: 2
   template:
     metadata:
       labels:
         app: web
     spec:
       containers:
         - name: crud-app
           image: tpageforfunzies/crudapp:v1
           ports:
             - containerPort: 5000
