---
apiVersion: v1
kind: Pod
metadata:
 name: crudapp
 labels:
   app: web
spec:
 containers:
   - name: crud-app
     image: crudapp:v3.2
     imagePullPolicy: Never
     ports:
       - containerPort: 5000